// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAimeRYdXC7LNR8N-T1QSRa7bLFnG0hLb0',
    appId: '1:772449112807:web:a49378a31bda5bd8780842',
    messagingSenderId: '772449112807',
    projectId: 'squeaky-database',
    authDomain: 'squeaky-database.firebaseapp.com',
    storageBucket: 'squeaky-database.appspot.com',
    measurementId: 'G-9XYNL8P90H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpSLx-MyICGLHFjTKxC9lrA4QKOU-HtoE',
    appId: '1:772449112807:android:1f457394562964d8780842',
    messagingSenderId: '772449112807',
    projectId: 'squeaky-database',
    storageBucket: 'squeaky-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5AEI8pPKIV5o-4SySgkT_Xw8K9Uuw_c',
    appId: '1:772449112807:ios:b35f72c476ea3b98780842',
    messagingSenderId: '772449112807',
    projectId: 'squeaky-database',
    storageBucket: 'squeaky-database.appspot.com',
    iosBundleId: 'com.example.squeakyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI5AEI8pPKIV5o-4SySgkT_Xw8K9Uuw_c',
    appId: '1:772449112807:ios:b35f72c476ea3b98780842',
    messagingSenderId: '772449112807',
    projectId: 'squeaky-database',
    storageBucket: 'squeaky-database.appspot.com',
    iosBundleId: 'com.example.squeakyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAimeRYdXC7LNR8N-T1QSRa7bLFnG0hLb0',
    appId: '1:772449112807:web:3e9524ab81dea3f5780842',
    messagingSenderId: '772449112807',
    projectId: 'squeaky-database',
    authDomain: 'squeaky-database.firebaseapp.com',
    storageBucket: 'squeaky-database.appspot.com',
    measurementId: 'G-383BE6P0ZZ',
  );

}